# Change these first
owner: hardixnph # Your GitHub organization or username, where this repository lives
repo: fastguard-uptime # The name of this repository

sites:
  - name: Database
    check: "tcp-ping"
    url: 116.203.189.202
    port: 3306
  - name: Homepage
    url: https://fastguard.ro
  - name: Pterodactyl
    url: https://pterodactyl.fastguard.ro
  - name: Germany Node
    check: "tcp-ping"
    url: 116.203.189.202
    port: 2022
  - name: Romania Node
    check: "tcp-ping"
    url: 80.97.49.110
    port: 2022
  - name: Mail
    check: "tcp-ping"
    url: 116.203.189.202
    port: 587
  - name: Webmail
    url: https://webmail.fastguard.ro
  - name: File Uploader
    url: https://i.fastguard.ro

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fastguard.ro
  theme: night
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FASTGUARD-Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page for FASTGUARD's related services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
